test

diff --git a/.github/workflows/run-script.yml b/.github/workflows/run-script.yml
--- a/.github/workflows/run-script.yml
+++ b/.github/workflows/run-script.yml
@@ -23,10 +23,18 @@ jobs:
         with:
             name: config.json
             json: ${{ secrets.CONFIG_JSON }}
-      
+      - name: Verify the Config is present and exit the workflow if it is not
+        run: |
+          if [ ! -f config.json ]; then
+             echo "::error::Config file is not present"
+             exit 1
+          fi
+        shell: bash
+
       - name: Perform Shell command
         run: ls -la
         shell: bash
+
 
       - name: Run test script
         run: node test-script.js
